### ISSUE TITLE
getRunningAppProcesses could return null

### ISSUE THREAD

**Issue by QponyDev** [sensorberg-dev/android-sdk#144]
### Crash possibility

Method `getRunningAppProcesses` used in [this place](https://github.com/sensorberg-dev/android-sdk/blob/531265020355a3334244406adae57fa1192755a6/android-sdk/src/main/java/com/sensorberg/SensorbergSdk.java#L302) may return null as documentation notes [here](https://developer.android.com/reference/android/app/ActivityManager.html#getRunningAppProcesses()) 

>  or null if there are no running processes (it will not return an empty list)

I suggest use code simmilar to [this ](https://github.com/JakeWharton/ProcessPhoenix/pull/17/commits/f4091b8803f1c582c43c8904f838ebd9b7bbcb12#diff-2242f5c7ec0344eb9131dea8e61bab31R111)

**Comment by budius** [comment]
https://github.com/sensorberg-dev/android-sdk/pull/145
