### ISSUE TITLE
Crash sensorbgerg android framework (android 6.0.1)

### ISSUE THREAD

**Issue by felixgillen** [sensorberg-dev/android-sdk#42]
We are getting bug reports from time to time on our sensorberg android integration with the following stack trace:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.bluetooth.BluetoothAdapter$LeScanCallback.onLeScan(android.bluetooth.BluetoothDevice, int, byte[])' on a null object reference
>        at com.sensorberg.bluetooth.CrashCallBackWrapper.onLeScan(CrashCallBackWrapper.java:59)
>        at android.bluetooth.BluetoothAdapter$4.onScanResult(BluetoothAdapter.java:3261)
>        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:413)
>        at android.os.Handler.handleCallback(Handler.java:739)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:158)
>        at android.app.ActivityThread.main(ActivityThread.java:7224)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Could you please have look?

Thanks,
Felix

**Comment by skraynick** [comment]
@felixgillen we will have a look. Thank you for your report.

**Comment by hoeggi** [comment]
this looks like some regression https://github.com/sensorberg-dev/android-sdk/issues/11

**Comment by mrsasha** [comment]
@felixgillen what SDK version are you using?

**Comment by felixgillen** [comment]
@mrsasha 

compile 'com.sensorberg.sdk:android-sdk-bootstrapper:2.0.0'
compile 'com.sensorberg.sdk:android-sdk:1.0.5RC4'

Best,
Felix

**Comment by skraynick** [comment]
@felixgillen our latest latest is 2.0.0RC7 but as labelled this is a release candidate and we are still testing, but it certainly can be used. The latest stable is 1.2.0. We should have a full 2.0.0 out either tomorrow or early next week.  Please check the github page releases page https://github.com/sensorberg-dev/android-sdk/releases or bintray for the recent releases. Also for the latest 2.0rc you will not need the bootstrapper compile. Full implementation instructions will follow with the release. Please let us know if you have any further questions or concerns.

Sarah

**Comment by felixgillen** [comment]
Thanks :)
Felix
