### ISSUE TITLE
Add warning to readme about Build-Tools 1.4.0

### ISSUE THREAD

**Issue by hoeggi** [sensorberg-dev/android-sdk#8]
Because of this Bug: https://code.google.com/p/android/issues/detail?id=188237 the SDK doesn't work with Build-Tools 1.4. 

When build this way the final APK is missing the realm.io binaries and crashes with a UnsatisfiedLinkError.

Please add a warning about this to the readme or if you want I can send a Pull-Request.

**Comment by falkorichter** [comment]
Is there a fix? Or is the final Build-Tools 1.4 broken? 

So building with Build-Tools 1.4 breaks the build if you include the Sensorberg SDK. I fear a simple warning in the Readme will not be enough :(

**Comment by hoeggi** [comment]
it works with 1.3 and is already fixed with 1.5 only breaks the build on 1.4

**Comment by hoeggi** [comment]
so i guess a warning  just not to use 1.4 should be enougth

**Comment by hoeggi** [comment]
i guess this can be closed, since it almost a year and we are on 2.2+ already. no one should be using 1.4 by now
