### ISSUE TITLE
Unable to detect beacon

### ISSUE THREAD

**Issue by swatipuchd** [sensorberg-dev/android-sdk#9]
Hi,
I am unable to get any response from Sensorberg demo. No beacon detection is there. Please help me in this matter.

Thanks.

**Comment by falkorichter** [comment]
Please contact support@sensorberg.com or provide further information. What device are you using? Which beacons? Have you tried the [Sensorberg Showcase application](https://play.google.com/store/apps/details?id=com.sensorberg.android.showcase&hl=de)? What system status does that app show you?
